Funcion para agregar columnas y sus distintas subfuncionalidades.
FundacioEsplaiJava2024/ToDoListGrupo4 pull request #28
Opened 2024-06-20 10:13 UTC by kianMIC

Se implemento correctamente la funcion de mover columnas, y sus subfuncionalidades, tales como la de editar columna, y eliminar columna.

#14

2024-06-20 11:17 UTC, SaraVictorFernandez requested changes
Se tienen que arreglar algunas cosas. Principalmente, en el componente Tablero habéis dejado de usar las tareas que se pasan desde App (por lo que usan las tareas que gestiona el useTaskManager y ha quedado obsoleto porque no tiene en cuenta las columnas).

Si el código (useTaskManager) ya no tiene utilidad, borradlo. Y si el problema es que el hook de useTaskManager tiene que evolucionar para gestionar las columnas y que el tablero simplemente pinte las cosas y avise a App, entonces tenéis que hacer un refactor y mover las cosas de sitio.

2024-06-20 11:17 UTC, SaraVictorFernandez commented on src/App.tsx
> -import './Elementos/fontAwesomeSetup';
ya no usáis la fontAwesome?

2024-06-20 11:17 UTC, SaraVictorFernandez commented on src/Elementos/tablero.tsx
> +    const nuevaColumnaId = Date.now(); // Genera un ID único basado en la fecha y hora actual
usar la hora para generar ids es mala práctica, puesto que no garantiza que los ids sean únicos. Usad un UUID

2024-06-20 11:17 UTC, SaraVictorFernandez commented on src/Elementos/tablero.tsx
> +  tasks: { id: number; name: string }[];
dónde usáis las tareas que vienen del componente padre?

En caso que las uséis (que no), cómo gestionáis la información de en qué columna tienen que aparecer?

2024-06-20 11:17 UTC, SaraVictorFernandez commented on src/Elementos/tablero.tsx
> +    deleteTask(taskId, columnaId);
no importa que el "padre" borre una tarea, si no estáis haciendo caso a estas tareas

2024-06-20 11:17 UTC, SaraVictorFernandez commented on src/Elementos/tablero.tsx
> +    editTask(taskId, newName);
lo mismo que en el delete; no importa que el "padre" edite la tarea, si esas tareas no se usan

2024-06-20 18:09 UTC, AlexFlFe commented on src/App.tsx
> -import './Elementos/fontAwesomeSetup';
Fixed

2024-06-20 18:10 UTC, AlexFlFe commented on src/Elementos/tablero.tsx
> +    const nuevaColumnaId = Date.now(); // Genera un ID único basado en la fecha y hora actual
Fixed, ahora utiliza uuidv4 en vez de date.

2024-06-20 18:11 UTC, AlexFlFe commented on src/Elementos/tablero.tsx
> +    deleteTask(taskId, columnaId);
Fixed, ahora el hook contiene bien los métodos y se utilizan desde ahí.

2024-06-20 18:11 UTC, AlexFlFe commented on src/Elementos/tablero.tsx
> +    editTask(taskId, newName);
Lo mismo que arriba

2024-06-20 18:37 UTC, AlexFlFe commented
@SaraVictorFernandez Hemos arreglado los cambios, puedes volver a revisar la PR, por favor?

2024-06-20 21:07 UTC, SaraVictorFernandez approved these changes

2024-06-20 21:14 UTC, AlexFlFe approved these changes

2024-06-20 21:26 UTC, kianMIC commented
Alex anda carreando a todo el equipo en su espalda, que crack, el codigo esta genial, gracias !!!

2024-06-20 21:29 UTC, Albamph approved these changes

2024-06-20 22:07 UTC, JordiJT99 approved these changes

2024-06-20 22:08 UTC, JordiJT99 approved these changes

2024-06-21 07:16 UTC, AleXKiD31 approved these changes

2024-06-21 07:18 UTC, merged