Creación de contador y funcionalidad de botón
FundacioEsplaiJava2024/ToDoListGrupo4 pull request #6
Opened 2024-06-10 08:06 UTC by JordiJT99

Se crea un contador para saber cuantas tareas hay, un cuadro de texto para poner el nombre de la tarea y un botón para borrar la tarea deseada. Además se añade explicación del código.

2024-06-10 08:08 UTC, JordiJT99 reviewed
Código subido

2024-06-10 08:09 UTC, Albamph approved these changes
Gracias por añadir los comentarios, queda mucho más claro! Lo veo bien!

2024-06-10 08:09 UTC, AleXKiD31 commented
Se ve bien para mi.

2024-06-10 08:09 UTC, AleXKiD31 approved these changes

2024-06-10 08:10 UTC, kianMIC approved these changes

2024-06-10 08:13 UTC, AlexFlFe approved these changes
Looks very good. Thank you for adding comments to your code so I can understand it much better.

2024-06-10 08:26 UTC, SaraVictorFernandez reviewed
This PR adds functionality (it's not just about refactoring or cleaning code).

What task is it related to? What structure are we following?

2024-06-10 11:35 UTC, SaraVictorFernandez requested changes
great idea to have a hook "useTaskManager", but it's not on the right file (or folder)

App.tsx is still trying to paint lists and does things that should be delegated to other components

2024-06-11 07:22 UTC, kianMIC commented on src/Elementos/Columna.js
andamos en ello ;-;

2024-06-11 07:45 UTC, kianMIC commented
Acabo re realizar un refactor que soluciona lo relacionado con el issue #7

2024-06-11 08:11 UTC, AlexFlFe approved these changes

2024-06-11 08:12 UTC, JordiJT99 reviewed
Buenos cambios separando columnas y funcionalidad en archivos separados para que la app se vea más nítida.Gracias.

2024-06-11 08:13 UTC, Albamph approved these changes
Lo veo bien, merci!

2024-06-11 08:19 UTC, JordiJT99 commented on src/Elementos/Columna.tsx
Cambiaremos el nombre de la clase a tablero para que sea más concreto a lo que se refiere.

2024-06-11 08:24 UTC, SaraVictorFernandez commented on src/Elementos/Columna.tsx
Ok, actualizad la PR con este cambio please

2024-06-11 08:25 UTC, JordiJT99 commented on src/App.tsx
Define la estructura de la aplicacion exportando las clases de TaskManager y Tablero. Es el contenedor donde funcionan las clases.

2024-06-14 09:03 UTC, JordiJT99 commented
Añadir funcionalidades de addTask, deleteTask, editTask, para añadir,eliminar y editar las tareas respectivamente además de tener un contador para saber el número total de tareas que hay. Añadir tarea se realiza a través de un botón de "+" escribiendo el nombre en un campo de texto, eliminar con un botón de borrar y editar con un botón de borrar que te dejará guardar los cambios o cancelar la edición

2024-06-14 09:13 UTC, kianMIC commented
codigo funcional, bastante bien implementado, tomar en cuenta cambio de botones a futuro.

2024-06-14 09:14 UTC, kianMIC approved these changes

2024-06-14 09:14 UTC, JordiJT99 reviewed
Código subido

2024-06-14 09:14 UTC, SaraVictorFernandez approved these changes
looks good to me

2024-06-14 09:14 UTC, SaraVictorFernandez commented on src/Elementos/tablero.tsx
> +interface ColumnaProps {
No es un tablero?

2024-06-14 09:14 UTC, SaraVictorFernandez commented on src/Elementos/tablero.tsx
> +const Columna: React.FC<ColumnaProps> = ({ count, tasks, taskName, handleInputChange, addTask, deleteTask, editTask }) => {
Columna? O tablero?

2024-06-14 09:15 UTC, AlexFlFe approved these changes
Ya refactorizaremos luego el código. De momento perfecto 👍

2024-06-14 09:16 UTC, AleXKiD31 approved these changes
Lo veo bien.

2024-06-14 10:33 UTC, JordiJT99 reviewed
Se han cambiado las variables columnas por tablero para que quede más preciso con la funcionalidad del fichero

2024-06-14 10:33 UTC, merged